
#ifndef VARIADIC_APPLY_H
#define VARIADIC_APPLY_H

#define PARENTHESIS_HELPER ()
#define MACRO_EXPAND1(...) \
  __VA_ARGS__
#define MACRO_EXPAND2(...) \
  MACRO_EXPAND1(MACRO_EXPAND1(MACRO_EXPAND1(MACRO_EXPAND1(__VA_ARGS__))))
#define MACRO_EXPAND3(...) \
  MACRO_EXPAND2(MACRO_EXPAND2(MACRO_EXPAND2(MACRO_EXPAND2(__VA_ARGS__))))
#define MACRO_EXPAND4(...) \
  MACRO_EXPAND3(MACRO_EXPAND3(MACRO_EXPAND3(MACRO_EXPAND3(__VA_ARGS__))))
#define MACRO_EXPAND5(...) \
  MACRO_EXPAND4(MACRO_EXPAND4(MACRO_EXPAND4(MACRO_EXPAND4(__VA_ARGS__))))
#define MACRO_EXPAND(...) \
  MACRO_EXPAND5(__VA_ARGS__)

#define APPLY_N(macro, ...) MACRO_EXPAND(APPLY_N_HELPER(macro, __VA_ARGS__))
#define APPLY_N_HELPER(macro, arg, ...) macro(arg) \
    __VA_OPT__(APPLY_N_HELPER_INVOKE PARENTHESIS_HELPER(macro, __VA_ARGS__))
#define APPLY_N_HELPER_INVOKE() APPLY_N_HELPER

#define COUNT_ONE_MACRO(x) +1
#define COUNT_ARGS(...) (__VA_OPT__(APPLY_N(COUNT_ONE_MACRO, __VA_ARGS__)))
#define comp_if(bool, then, else) \
  __builtin_choose_expr(bool, then, else)

#endif // VARIADIC_APPLY_H
